version: '3.4'

services:
  frontend:
    image: certificationcenterfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888
    env_file:
      - .env
