version: '3.4'

services:
  certificationcenterfrontend:
    image: certificationcenterfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443