version: '3.4'

services:
  certificationcenterfrontend:
    image: certificationcenterfrontend
    build:
      context: .
      args:
        - CACHEBUST=$$(date +%s)
      dockerfile: ./Dockerfile
    ports:
      - 8777:80